### ISSUE TITLE
Compilation Error on Xcode 13.4

### ISSUE THREAD

**Issue by indraneel-hs** [AlphaWallet/alpha-wallet-ios#5477]
Im getting compilation error in SelectableSwapRouteTableViewCellViewModel.swift file

Cannot infer return type for closure with multiple statements; add explicit type to disambiguate

[https://imgur.com/a/2GG7RP8](url)

**Comment by hboon** [comment]
Can you try Xcode 13.3.1 to see if it makes a difference? That's our official version until we switch formally to 14.x (it apparently works with 14.0 too)

**Comment by hboon** [comment]
(the screenshot link is broken)

**Comment by oa-s** [comment]
Close as fixed
